# Generated by Django 3.0.2 on 2020-03-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pencilsketch',
            name='original_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pencilsketch',
            name='sketch_image',
            field=models.ImageField(upload_to='edited_images'),
        ),
    ]
