# Generated by Django 3.0.2 on 2020-04-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketcher', '0002_auto_20200318_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pencilsketch',
            name='sketch_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
